-- DoctorPet 병원 확정 예약 취소 운영 DB 마이그레이션
-- 적용 전: 전체 백업 생성 후 스테이징에서 동일 SQL과 관련 통합 테스트를 실행한다.
-- 적용 중: reservations/reservation_events/notifications ALTER 잠금과 대기 세션을 모니터링한다.
-- 적용 후: 컬럼·ENUM·레거시 값 변환 결과와 애플리케이션 기동 로그를 확인한다.

ALTER TABLE reservations
    ADD COLUMN IF NOT EXISTS hospital_cancel_reason VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS hospital_canceled_at DATETIME(6) NULL;

ALTER TABLE reservations
    MODIFY COLUMN status ENUM(
        'CANCELED', 'CHECKED_IN', 'CONFIRMED', 'HOSPITAL_CANCELLED', 'HOSPITAL_CANCELED',
        'IN_TREATMENT', 'NO_SHOW', 'NO_SHOW_PENDING', 'REJECTED',
        'REQUESTED', 'TREATMENT_COMPLETED'
    ) NOT NULL;

UPDATE reservations
   SET status = 'HOSPITAL_CANCELED'
 WHERE status = 'HOSPITAL_CANCELLED';

ALTER TABLE reservations
    MODIFY COLUMN status ENUM(
        'CANCELED', 'CHECKED_IN', 'CONFIRMED', 'HOSPITAL_CANCELED',
        'IN_TREATMENT', 'NO_SHOW', 'NO_SHOW_PENDING', 'REJECTED',
        'REQUESTED', 'TREATMENT_COMPLETED'
    ) NOT NULL;

ALTER TABLE reservation_events
    MODIFY COLUMN event_type ENUM(
        'AUTO_NO_SHOW', 'AUTO_NO_SHOW_PENDING', 'CHECKED_IN',
        'HOSPITAL_CANCELLED', 'HOSPITAL_CANCELED', 'MANUAL_NO_SHOW', 'NO_SHOW_CORRECTED',
        'TIMEOUT_REJECTED'
    ) NOT NULL;

UPDATE reservation_events
   SET event_type = 'HOSPITAL_CANCELED'
 WHERE event_type = 'HOSPITAL_CANCELLED';

ALTER TABLE reservation_events
    MODIFY COLUMN event_type ENUM(
        'AUTO_NO_SHOW', 'AUTO_NO_SHOW_PENDING', 'CHECKED_IN',
        'HOSPITAL_CANCELED', 'MANUAL_NO_SHOW', 'NO_SHOW_CORRECTED',
        'TIMEOUT_REJECTED'
    ) NOT NULL;

ALTER TABLE notifications
    MODIFY COLUMN type ENUM(
        'NO_SHOW', 'PAYMENT_RESULT', 'RESERVATION_CONFIRMED',
        'RESERVATION_HOSPITAL_CANCELLED', 'RESERVATION_HOSPITAL_CANCELED',
        'RESERVATION_REJECTED'
    ) NOT NULL;

UPDATE notifications
   SET type = 'RESERVATION_HOSPITAL_CANCELED'
 WHERE type = 'RESERVATION_HOSPITAL_CANCELLED';

ALTER TABLE notifications
    MODIFY COLUMN type ENUM(
        'NO_SHOW', 'PAYMENT_RESULT', 'RESERVATION_CONFIRMED',
        'RESERVATION_HOSPITAL_CANCELED', 'RESERVATION_REJECTED'
    ) NOT NULL;
